# Generated by Django 6.0.1 on 2026-01-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitantes',
            new_name='Visitante',
        ),
    ]
