# Generated by Django 6.0.1 on 2026-01-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
        ('visitantes', '0002_rename_visitantes_visitante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitante',
            new_name='Visitantes',
        ),
    ]
