# Generated by Django 6.0.1 on 2026-01-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_rename_visitante_visitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('EM_VISITA', 'Em visita'), ('FINALIZADO', 'Visita finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status do visitante'),
        ),
    ]
