# Generated by Django 6.0.1 on 2026-01-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_visitantes_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitantes',
            old_name='horario_auturizacao',
            new_name='horario_autorizacao',
        ),
    ]
